/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * QROrder API
 * QROrder Management System API 문서
 * OpenAPI spec version: v1.0
 */

export interface FileInfo {
  sysId?: string;
  linkSysId?: string;
  originalFileNm?: string;
  convertFileNm?: string;
  fileExt?: string;
  mimeType?: string;
  fileSize?: string;
  filePath?: string;
  ordNo?: number;
  pdfYn?: string;
}
