/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * QROrder API
 * QROrder Management System API 문서
 * OpenAPI spec version: v1.0
 */

export interface Menu {
  sysId?: string;
  menuCd: string;
  menuNm: string;
  parentMenuCd: string;
  ordNo: string;
  treeLevel: string;
  menuUrl?: string;
}
