/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * QROrder API
 * QROrder Management System API 문서
 * OpenAPI spec version: v1.0
 */

export interface Payment {
  sysId?: string;
  plantCd: string;
  paymentCd: string;
  paymentNm: string;
  paymentFee: number;
  paymentFeeUnit: string;
  licenseValidMonth: number;
}
